export const mockApplications = [
  {
    id: 1,
    jobTitle: "Frontend Developer",
    company: "TechCorp India",
    status: "interview",
    appliedDate: "2026-05-01",
    lastUpdated: "2026-05-08",
    notes: "Had initial phone screen. Technical round scheduled for May 12.",
    timeline: [
      { date: "2026-05-01", event: "Applied", status: "applied" },
      { date: "2026-05-03", event: "Recruiter viewed profile", status: "applied" },
      { date: "2026-05-05", event: "Phone screen scheduled", status: "assessment" },
      { date: "2026-05-08", event: "Phone screen completed, moving to technical", status: "interview" },
    ],
  },
  {
    id: 2,
    jobTitle: "React Developer",
    company: "StartupXYZ",
    status: "applied",
    appliedDate: "2026-05-03",
    lastUpdated: "2026-05-03",
    notes: "Applied through company career page. Referral from LinkedIn contact.",
    timeline: [
      { date: "2026-05-03", event: "Applied via career page", status: "applied" },
    ],
  },
  {
    id: 3,
    jobTitle: "Junior Software Engineer",
    company: "Infosys",
    status: "assessment",
    appliedDate: "2026-04-28",
    lastUpdated: "2026-05-06",
    notes: "Online coding test link received. HackerRank assessment due by May 10.",
    timeline: [
      { date: "2026-04-28", event: "Applied through Naukri", status: "applied" },
      { date: "2026-05-02", event: "Application acknowledged", status: "applied" },
      { date: "2026-05-06", event: "Coding assessment sent", status: "assessment" },
    ],
  },
  {
    id: 4,
    jobTitle: "UI Engineer",
    company: "DesignStudio",
    status: "rejected",
    appliedDate: "2026-04-20",
    lastUpdated: "2026-05-04",
    notes: "Rejected after technical round. Feedback: need more experience with design systems.",
    timeline: [
      { date: "2026-04-20", event: "Applied via LinkedIn", status: "applied" },
      { date: "2026-04-25", event: "Initial screening call", status: "assessment" },
      { date: "2026-04-30", event: "Technical interview", status: "interview" },
      { date: "2026-05-04", event: "Rejection email received", status: "rejected" },
    ],
  },
  {
    id: 5,
    jobTitle: "Full Stack Developer",
    company: "CloudNine Services",
    status: "offer",
    appliedDate: "2026-04-15",
    lastUpdated: "2026-05-07",
    notes: "Offer letter received! 8 LPA CTC. Need to respond by May 15.",
    timeline: [
      { date: "2026-04-15", event: "Applied", status: "applied" },
      { date: "2026-04-18", event: "Phone screen", status: "assessment" },
      { date: "2026-04-22", event: "Technical round 1", status: "interview" },
      { date: "2026-04-28", event: "Technical round 2 + HR", status: "interview" },
      { date: "2026-05-07", event: "Offer letter received", status: "offer" },
    ],
  },
  {
    id: 6,
    jobTitle: "JavaScript Developer",
    company: "Digital Agency Pro",
    status: "saved",
    appliedDate: null,
    lastUpdated: "2026-05-07",
    notes: "Interesting role. Need to tailor resume before applying.",
    timeline: [],
  },
  {
    id: 7,
    jobTitle: "Software Developer Trainee",
    company: "TCS",
    status: "ghosted",
    appliedDate: "2026-04-10",
    lastUpdated: "2026-04-10",
    notes: "No response after 4 weeks. Likely ghosted.",
    timeline: [
      { date: "2026-04-10", event: "Applied through TCS NextStep", status: "applied" },
    ],
  },
  {
    id: 8,
    jobTitle: "Web Developer Intern",
    company: "LearnTech",
    status: "applied",
    appliedDate: "2026-05-06",
    lastUpdated: "2026-05-06",
    notes: "3-month internship. Stipend 15k/month.",
    timeline: [
      { date: "2026-05-06", event: "Applied via Internshala", status: "applied" },
    ],
  },
];

export const applicationStatuses = [
  "all",
  "saved",
  "applied",
  "assessment",
  "interview",
  "rejected",
  "ghosted",
  "offer",
];
