export const mockJobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechCorp India",
    source: "LinkedIn",
    relevanceScore: 92,
    scamScore: 5,
    status: "new",
    dateScraped: "2026-05-09",
    location: "Bangalore",
    type: "Full-time",
  },
  {
    id: 2,
    title: "React Developer",
    company: "StartupXYZ",
    source: "Naukri",
    relevanceScore: 87,
    scamScore: 12,
    status: "reviewed",
    dateScraped: "2026-05-09",
    location: "Remote",
    type: "Full-time",
  },
  {
    id: 3,
    title: "Junior Software Engineer",
    company: "Infosys",
    source: "Indeed",
    relevanceScore: 78,
    scamScore: 3,
    status: "new",
    dateScraped: "2026-05-08",
    location: "Hyderabad",
    type: "Full-time",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "WebSolutions",
    source: "LinkedIn",
    relevanceScore: 85,
    scamScore: 45,
    status: "flagged",
    dateScraped: "2026-05-08",
    location: "Mumbai",
    type: "Full-time",
  },
  {
    id: 5,
    title: "JavaScript Developer",
    company: "Digital Agency Pro",
    source: "Glassdoor",
    relevanceScore: 73,
    scamScore: 8,
    status: "new",
    dateScraped: "2026-05-07",
    location: "Pune",
    type: "Contract",
  },
  {
    id: 6,
    title: "Web Developer Intern",
    company: "LearnTech",
    source: "Internshala",
    relevanceScore: 65,
    scamScore: 15,
    status: "reviewed",
    dateScraped: "2026-05-07",
    location: "Delhi",
    type: "Internship",
  },
  {
    id: 7,
    title: "Node.js Backend Developer",
    company: "CloudNine Services",
    source: "Naukri",
    relevanceScore: 81,
    scamScore: 7,
    status: "new",
    dateScraped: "2026-05-06",
    location: "Bangalore",
    type: "Full-time",
  },
  {
    id: 8,
    title: "MERN Stack Developer",
    company: "QuickHire",
    source: "Indeed",
    relevanceScore: 90,
    scamScore: 62,
    status: "flagged",
    dateScraped: "2026-05-06",
    location: "Remote",
    type: "Full-time",
  },
  {
    id: 9,
    title: "UI Engineer",
    company: "DesignStudio",
    source: "LinkedIn",
    relevanceScore: 88,
    scamScore: 4,
    status: "saved",
    dateScraped: "2026-05-05",
    location: "Bangalore",
    type: "Full-time",
  },
  {
    id: 10,
    title: "Software Developer Trainee",
    company: "TCS",
    source: "Naukri",
    relevanceScore: 70,
    scamScore: 2,
    status: "new",
    dateScraped: "2026-05-05",
    location: "Chennai",
    type: "Full-time",
  },
  {
    id: 11,
    title: "React Native Developer",
    company: "MobileFirst",
    source: "LinkedIn",
    relevanceScore: 76,
    scamScore: 9,
    status: "new",
    dateScraped: "2026-05-04",
    location: "Noida",
    type: "Full-time",
  },
  {
    id: 12,
    title: "Frontend Intern",
    company: "EduTech Solutions",
    source: "Internshala",
    relevanceScore: 60,
    scamScore: 20,
    status: "reviewed",
    dateScraped: "2026-05-04",
    location: "Remote",
    type: "Internship",
  },
];

export const jobStatuses = ["all", "new", "reviewed", "saved", "flagged"];
export const jobSources = ["all", "LinkedIn", "Naukri", "Indeed", "Glassdoor", "Internshala"];
